name: predictify
dependencies:
    - name: chainlink
      version: "1.3.0"
      github: smartcontractkit/chainlink

    - name: openzeppelin
      version: "4.7.0"
      github: OpenZeppelin/openzeppelin-contracts
